# roles/haproxy/tasks/main.yml

---

- name: Install HAProxy
  package:
    name: haproxy

- name: Allow service to start
  lineinfile:
    dest: /etc/default/haproxy
    regexp: ENABLED=.*
    line: ENABLED=1
  notify: reload HAProxy service
    
- name: Install configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: reload HAProxy service

- name: Start / enable HAProxy
  service:
    name: haproxy
    enabled: true
    state: started

- name: Include tests
  include_tasks: tests.yml
  tags: tests
