# install.yml

---
- hosts: all
  gather_facts: true

- hosts: load-balancers
  gather_facts: false
  become: true
  roles:
          - role: haproxy
            tags: haproxy

- hosts: app-servers
  gather_facts: false
  become: true
  roles:
          - role: tomcat
            tags: tomcat

